apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kaboom-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # CloudRun 最適化設定
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        
        # WebSocket長時間接続対応
        run.googleapis.com/timeout: "3600s"
        
    spec:
      # コンテナ設定
      containerConcurrency: 1000
      timeoutSeconds: 3600
      
      containers:
      - name: kaboom-api
        image: gcr.io/PROJECT_ID/kaboom-api:latest
        
        # リソース制限
        resources:
          limits:
            cpu: "2000m"
            memory: "4Gi"
          requests:
            cpu: "1000m"
            memory: "2Gi"
        
        # 環境変数
        env:
        - name: PORT
          value: "8080"
        - name: HOST
          value: "0.0.0.0"
        - name: DEBUG
          value: "false"
        - name: WS_MAX_CONNECTIONS
          value: "1000"
        - name: WS_HEARTBEAT_INTERVAL
          value: "30"
        - name: MARKET_DATA_UPDATE_INTERVAL
          value: "5"
        - name: SYSTEM_METRICS_UPDATE_INTERVAL
          value: "30"
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
        - name: CLOUD_RUN_SERVICE
          value: "kaboom-api"
        
        # シークレット（Secret Manager統合）
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: kaboom-secrets
              key: supabase_url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: kaboom-secrets
              key: supabase_anon_key
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: kaboom-secrets
              key: supabase_service_role_key
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: kaboom-secrets
              key: redis_url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: kaboom-secrets
              key: openai_api_key
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: kaboom-secrets
              key: gemini_api_key
        
        # ヘルスチェック
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        
        # ポート設定
        ports:
        - name: http1
          containerPort: 8080